### PR TITLE
Implement `buildsystem:role` Context for LuckPerms

### PR DESCRIPTION
**Pull request by einTosti**
Implements #56 

Introduces the `buildsystem:role` Context (requires LuckPerms).
Can have the following values:
- `creator`
- `builder`
- `guest`

**For example:** You want players who are guests in a world (neither _creator_ nor _builder_) to remain in the gamemode they currently are in.

Now you can use the following `Context`:
`/lp user <user> permission set buildsystem.gamemode false buildsystem:role=guest`

### CODE REVIEW

**Comment by einTosti** [comment]
I guess one could discuss if `guest` should be renamed to `visitor`?
CC: @TWME-TW

**Comment by TWME-TW** [comment]
> I guess one could discuss if `guest` should be renamed to `visitor`? CC: @TWME-TW

Ummm, I'm not quite sure about their differences in English...

**Comment by einTosti** [comment]
There isn't really a big difference. I just chose `guest` as it is often more intuitive

**Comment by TWME-TW** [comment]
> 

Then use `guest`!

**Pull request merged**
